skia: SkBlitter_ARGB32: Remove unused variable
external/skia/src/core/SkBlitter_ARGB32.cpp:573:16: error: unused variable 'span
' [-Werror,-Wunused-variable]
    SkPMColor* span = fBuffer;
               ^
1 error generated.

Change-Id: Ia31b96f9a874073e9eb2cdef89550701ab2b6981